### ISSUE TITLE
Matriz & coworking

### ISSUE THREAD

**Issue by kaiofelipejs** [guru-br/catalogo_empresas#47]
Fala pessoal! 
Subi um PR para adicionar a Resultados Digitais na lista das empresas, porém eu e o @odineiramone encontramos um probleminha. 
Na RD temos 3 escritórios disponíveis (geralmente damos liberdade para a pessoa escolher aonde quer ficar), são eles: **Florianópolis, Joinville e São Paulo**. Porém os escritórios de Joinville e São Paulo são apenas uma **extensão da matriz**. Não é uma filial diferente ou algo do tipo, apenas um _coworking/workplace_ diferente do de Floripa. 
Acredito que podemos criar uma regrinha para identificar na lista sem deixar desorganizado. O que acham?

**Comment by juuh42dias** [comment]
Acho que vale entrar em uma discussão pra uma versão 2.0 do catálogo.

Usando o exemplo da empresa Credere da qual tem a matriz em Natal - RN, filial usando um coworking em São Paulo - SP e pessoas remotas como eu em demais cidades. 

Caso esse espaço seja usado como escritório, conta-se como filial.
Caso esse espaço não seja usado fixamente como escritório, então não entra no critério.

**Comment by leandrogs** [comment]
Oi @kaiofelipejs, acho que por enquanto não é necessário identificar se é coworking ou não. Minha percepção é que colocar matriz/filial na frente do nome seja apenas para identificar onde é a sede da empresa.

**Comment by kaiofelipejs** [comment]
E aí @leandrogs! Susse então. Vou subir um PR pra adicionar a filial de SP da RD também então. Puxando o gancho da Credere citada pela @juuh42dias, vale alguma identificação para informar que contrata para vagas remotas? Temos outros casos assim, tipo a Codeminer. To pensando mais na visualização de quem está buscando vaga. O que acham?

**Comment by leandrogs** [comment]
Eu gostaria de ver quem contrata remoto ou não. Acho que na estrutura de hoje fica meio foda de colocar. Vamos encerrar essa issue e abrir uma discussão nova sobre como incluir remoto?
